version: '3.3'
services:
  backend:
    image: golang:1.19-alpine3.16
    container_name: golang
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_DB_HOST:${POSTGRES_DB_HOST}
      - POSTGRES_PORT:${POSTGRES_PORT}
      - REDIS_PORT:${REDIS_PORT}
      - REDIS_DB:${REDIS_DB}
      - REDIS_HOST:${REDIS_HOST}
      - REDIS_PASSWORD:${REDIS_PASSWORD}
    env_file:
      - .env
    build:
      context: .
      dockerfile: go.dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    command: "go run /app/main.go"
    depends_on:
      - postgresdb
      - keydb

  frontend:
    image: httpd:alpine
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    ports:
      - 8888:80
    restart: always

  postgresdb:
    image: postgres:latest
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./psql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 5

# KeyDB is used instead of redis
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    restart: always
    environment:
      - KEYDB_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    

volumes:
  postgres-data-volume: